=== deniszhylin/Java/data/task4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.exemple.com/task4"
           xmlns="http://www.example.com/task4">

    <xs:element name="paper" type="paperType" abstract="true"/>
    <xs:element name="newspaper" type="newspaperType" substitutionGroup="paper"/>
    <xs:element name="magazine" type="magazineType" substitutionGroup="paper"/>
    <xs:element name="booklet" type="bookletType" substitutionGroup="paper"/>

    <xs:element name="papers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="paper" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="paperType">
        <xs:sequence>
            <xs:element type="specicationsType" name="specications"/>
        </xs:sequence>
        <xs:attribute name="name" type="nameType" use="required"/>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="data" type="xs:string" use="required"
    </xs:complexType>

    <xs:complexType name="newspaperType">
        <xs:complexContent>
            <xs:extension base="paperType">
                <xs:sequence>
                    <xs:element type="xs:int" name="index"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="magazineType">
        <xs:complexContent>
            <xs:extension base="paperType">
                <xs:sequence>
                    <xs:element type="xs:int" name="index"/>
                    <xs:element type="xs:boolean" name="monthly"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="bookletType">
        <xs:complexContent>
            <xs:extension base="paperType">
                <xs:sequence>
                    <xs:element type="xs:boolean" name="monthly"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(.){1,25}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="id">
        <xs:restriction base="xs:ID">
            <xs:pattern value="x\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="specicationsType">
        <xs:sequence>
            <xs:element type="xs:string" name="color"/>
            <xs:element type="xs:boolean" name="coated"/>
            <xs:element type="xs:positiveInteger" name="pages"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== deniszhylin/Java/data/task4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<papers xmlns="http://www.example.com/task4"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.example.com/task4 task4.xsd">
    <newspaper name="The SUN" id="0001" date="2018-03-01">
        <index>11024</index>
        <specications>
            <color>false</color>
            <coated>false</coated>
            <pages>4</pages>
        </specications>
    </newspaper>

    <newspaper name="New York Times" id="0002" date="2018-03-01">
        <index>11255</index>
        <specications>
            <color>true</color>
            <coated>false</coated>
            <pages>6</pages>
        </specications>
    </newspaper>

    <newspaper name="Spigel" id="0003" date="2018-03-01">
        <index>11045</index>
        <specications>
            <color>true</color>
            <coated>false</coated>
            <pages>6</pages>
        </specications>
    </newspaper>

    <newspaper name="Wall Street Journal" id="0004" date="2018-03-01">
        <index>11078</index>
        <specications>
            <color>true</color>
            <coated>false</coated>
            <pages>10</pages>
        </specications>
    </newspaper>

    <newspaper name="Japan Today" id="0005" date="2018-03-01">
        <index>11456</index>
        <specications>
            <color>true</color>
            <coated>false</coated>
            <pages>12</pages>
        </specications>
    </newspaper>

    <newspaper name="Washington Post" id="0006" date="2018-03-01">
        <index>11458</index>
        <specications>
            <color>false</color>
            <coated>false</coated>
            <pages>6</pages>
        </specications>
    </newspaper>

    <magazine name="TV Magazine" id="0101" date="2018-03-01">
        <monthly>true</monthly>
        <index>10456</index>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>160</pages>
        </specications>
    </magazine>

    <magazine name="Elle" id="0102" date="2018-04-01">
        <monthly>true</monthly>
        <index>10547</index>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>130</pages>
        </specications>
    </magazine>

    <magazine name="Glamour" id="0103" date="2018-04-01">
        <monthly>true</monthly>
        <index>10254</index>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>120</pages>
        </specications>
    </magazine>

    <magazine name="Auto Plus" id="0104" date="2018-04-01">
        <monthly>true</monthly>
        <index>10257</index>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>150</pages>
        </specications>
    </magazine>

    <magazine name="Parents" id="0105" date="2018-07-01">
        <monthly>true</monthly>
        <index>10254</index>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>70</pages>
        </specications>
    </magazine>

    <magazine name="Capital" id="0106" date="2018-07-01">
        <monthly>true</monthly>
        <index>10485</index>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>100</pages>
        </specications>
    </magazine>

    <booklet name="Europe" id="1101" date="2018-01-01">
        <monthly>false</monthly>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>1</pages>
        </specications>
    </booklet>

    <booklet name="EuroStar" id="01102" date="2018-02-01">
        <monthly>false</monthly>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>1</pages>
        </specications>
    </booklet>

    <booklet name="Asia" id="01103" date="2018-03-01">
        <monthly>false</monthly>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>1</pages>
        </specications>
    </booklet>

    <booklet name="Africa" id="01104" date="2018-02-01">
        <monthly>false</monthly>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>1</pages>
        </specications>
    </booklet>

    <booklet name="EuroStar" id="01105" date="2018-01-01">
        <monthly>false</monthly>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>1</pages>
        </specications>
    </booklet>

    <booklet name="Moskov" id="01106" date="2018-03-03">
        <monthly>false</monthly>
        <specications>
            <color>true</color>
            <coated>true</coated>
            <pages>1</pages>
        </specications>
    </booklet>
</papers>
